FROM balenalib/%%BALENA_MACHINE_NAME%%-debian:bookworm-run

RUN install_packages x11vnc \
    x11-utils \
    xvfb \
    wmctrl \
    supervisor

WORKDIR /usr/src/app

COPY . .

ADD supervisor /etc/supervisor

CMD ["bash", "start.sh"]